backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'Settings'
    label: 'settings'
    folder: 'content/settings'
    format: 'frontmatter'
    create: true
    slug: 'settings'
    editor:
      preview: false
    fields:
      - { label: 'Site Name', name: 'site_name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - label: 'Social'
        name: 'social'
        widget: list
        fields:
          - label: 'Social Media'
            name: 'social_media'
            widget: object
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }

  - name: 'home'
    label: 'Home'
    folder: 'content/home'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Banner'
        name: 'banner'
        widget: 'object'
        fields:
        - {label: Image, name: image, widget: image}
        - {label: Banner Text, name: banner_text, widget: string}
  - name: 'index'
    label: 'Index'
    folder: 'content/index'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Banner'
        name: 'banner'
        widget: 'object'
        fields:
        - {label: Image, name: image, widget: image}
        - {label: Banner Text, name: banner_text, widget: string}
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Featured Image', name: 'featured-image', widget: 'image' }
      - label: 'Page Section'
        name: 'sections'
        widget: 'list'
        types:
          - label: 'Text Block'
            name: 'text_block'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Text, name: text, widget: markdown }
          - label: 'Carousel'
            name: 'carousel'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Text, name: text, widget: markdown }
              - label: 'Images'
                name: images
                widget: list
                fields:
                  - { label: "Image", name: "image", widget: "image", required: false }
                  - { label: Image Description, name: alt, widget: string }
          - label: 'Block List'
            name: 'block_list'
            widget: object
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Text, name: text, widget: markdown, required: false }
              - label: 'Blocks'
                name: blocks
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Text, name: text, widget: markdown }
  - name: 'products'
    label: 'Products'
    folder: 'content/products'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Short Description', name: 'short_description', widget: 'string' }
      - { label: 'Featured Image', name: 'featured-image', widget: 'image' }
      - { label: 'Price', name: 'price', widget: 'number', min: 0, value_type: float }
      - label: 'Page Section'
        name: 'sections'
        widget: 'list'
        types:
          - label: 'Text Block'
            name: 'text_block'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Text, name: text, widget: markdown }
          - label: 'Carousel'
            name: 'carousel'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Text, name: text, widget: markdown }
              - label: 'Images'
                name: images
                widget: list
                fields:
                  - { label: "Image", name: "image", widget: "image", required: false }
                  - { label: Image Description, name: alt, widget: string }
          - label: 'Block List'
            name: 'block_list'
            widget: object
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Text, name: text, widget: markdown, required: false }
              - label: 'Blocks'
                name: blocks
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Text, name: text, widget: markdown }
  - name: 'flexible page'
    label: 'Flexible Page'
    folder: 'content/flexible'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'featured-image', widget: 'image' }
      - label: 'Flexible Section'
        name: 'sections'
        widget: 'list'
        types:

          - label: 'Text Block'
            name: 'text_block'
            widget: object
            fields:
              - { label: Text, name: text, widget: markdown }

          - label: 'Image'
            name: 'image'
            widget: object
            fields:
              - { label: Full Width, name: full_width, widget: boolean, required: false }
              - { label: Image, name: image, widget: image }
              - { label: Image Description, name: alt, widget: string }
                  
          - label: 'Image by Text'
            name: 'image_by_text'
            widget: object
            fields:
              - { label: Text, name: text, widget: markdown }
              - label: 'Image'
                name: 'image'
                widget: object
                fields:
                  - { label: Image, name: image, widget: image }
                  - { label: Image Description, name: alt, widget: string }
              - label: 'Button'
                name: 'button'
                widget: object
                fields:
                  - { label: Text, name: text, widget: string }
                  - { label: External Link, name: external_link, widget: boolean, required: false }
                  - { label: Link, name: link, widget: string }
                  
          - label: 'Carousel'
            name: 'carousel'
            widget: object
            fields:
              - label: 'Full Width'
                name: 'full_width'
                widget: boolean
                default: false
              - label: 'Slides'
                name: 'slides'
                widget: list
                fields:
                - { label: Text, name: text, widget: text }
                - label: 'Image'
                  name: 'image'
                  widget: object
                  fields:
                    - { label: Image, name: image, widget: image }
                    - { label: Image Description, name: alt, widget: string }
                - label: 'Button'
                  name: 'button'
                  widget: object
                  fields:
                    - { label: Text, name: text, widget: string }

          - label: 'Video'
            name: 'video'
            widget: object
            fields:
            - { label: 'Youtube Embed', name: 'youtube_embed', widget: string }